version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URI

  build:
    commands:
      - cd ./app
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile -t demo/todo-list-app:$IMAGE_TAG .
      - docker tag demo/todo-list-app:$IMAGE_TAG $IMAGE_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG
