apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: todo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deploymnet
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: 314146329889.dkr.ecr.us-west-2.amazonaws.com/todo-repo-imagerepositorye580bc5f-bgbvxhovz7ro:latest
        ports:
        - containerPort: 3000
